[package]
name = "py_osuparse"
version = "1.0.0"
authors = ["Rafael Castillo <rafael@trfs.me>"]

[lib]
name = "osuparse"
crate-type = ["rlib", "cdylib"]

[dependencies]
osuparse = { path = "../" }
rayon = "1.0.3"

[dependencies.cpython]
version = "0.2"
default-features = false
