[package]
name = "osuparse"
license = "GPL-3.0-or-later"
version = "0.1.1"
authors = ["Rafael Castillo <rafael@trfs.me>"]
description = "Crate for parsing osu! beatmaps."

[dependencies]
regex = "1"
lazy_static = "1.2.0"

